# -*- coding: utf-8 -*-
"""using of hugging face models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPkFMJZJsL6-1EK5ZCTVVxt9UaCWN96j
"""

!pip install transformers torch

from transformers import pipeline

# Load the summarization pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Your input text
text = """
Artificial intelligence (AI) is a rapidly advancing field that focuses on creating intelligent machines that work and learn like humans.
It encompasses a variety of subfields such as machine learning, natural language processing, robotics, and computer vision.
Applications of AI range from personal assistants and recommendation systems to autonomous vehicles and medical diagnostics.
As AI technologies become increasingly integrated into society, they raise ethical, legal, and societal challenges that must be addressed.
"""

# Generate summary
summary = summarizer(text, max_length=80, min_length=25, do_sample=False)

# Print summary
print("Summary:", summary[0]['summary_text'])

from transformers import pipeline

# Load NER pipeline
ner = pipeline("ner", grouped_entities=True)

# Run NER
text = "Barack Obama was born in Hawaii and was the 44th president of the USA."
entities = ner(text)

# Output
print(entities)

from transformers import pipeline

# Explicitly specify the model and use new aggregation strategy
ner = pipeline("ner", model="dbmdz/bert-large-cased-finetuned-conll03-english", aggregation_strategy="simple")

text = "Barack Obama was born in Hawaii and was the 44th president of the USA."

entities = ner(text)

for entity in entities:
    print(entity)

from google.colab import files
from PIL import Image

uploaded = files.upload()

for filename in uploaded.keys():
    image = Image.open(filename)

    from transformers import pipeline
    classifier = pipeline("image-classification")
    results = classifier(image)

    for result in results:
        print(f"{result['label']}: {round(result['score'], 3)}")

from diffusers import StableDiffusionPipeline
import torch
from PIL import Image

# Load model
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

# Your statement
prompt = "A girl studying"

# Generate image
image = pipe(prompt).images[0]

# Show image
image.show()

from matplotlib import pyplot as plt

image = pipe(prompt).images[0]

# Show with matplotlib
plt.imshow(image)
plt.axis("off")
plt.show()

from diffusers import StableDiffusionPipeline
import torch
from matplotlib import pyplot as plt

# Load the model (only once)
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

# Define prompt
prompt = "A majestic lion wearing a crown in a fantasy jungle"

# Generate image
image = pipe(prompt).images[0]

# Display image using matplotlib
plt.imshow(image)
plt.axis("off")
plt.show()

import transformers
from transformers import pipeline
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on Mars"
image = pipe(prompt).images[0]
from matplotlib import pyplot as plt

plt.imshow(image)
plt.axis("off")
plt.show()


image.save("astronaut_rides_horse.png")

en_fr_translator = pipeline("translation_en_to_fr")
response= en_fr_translator("Good Morning ")

print(response)

from transformers import pipeline

# Load translation pipeline
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-ur")

# Translate English to Urdu
sentence = "How are you? Hope you're doing well."
translated = translator(sentence, max_length=100)

# Print result
print("Urdu Translation:", translated[0]['translation_text'])